name: Test Modular Ochestration

on:
  - push

  
jobs:
  test:
    uses: DoubtfulJerboa/jsaction/.github/workflows/compile-py-service-installer.yml@callableworkflow
    permissions:
      contents: write # required for creating a release
    with:
      PYTHON_VERSION: 3.11.4
      REQUIREMENTS_PATH: ./requirements.txt
      ISS_PATH: ./setup.iss

    secrets: inherit