name: Test Modular Ochestration

on:
  - push

env:
  PYTHON_VERSION: 3.11.4
jobs:
  test:
    runs-on: windows-2022
    name: test goooo
    steps:
      - uses: actions/checkout@v4
      - uses: DoubtfulJerboa/jsaction/actions/python-embed-setup@v11
        with:
          PYTHON_VERSION: 3.12.4
          REQUIREMENTS_PATH: ./requirements.txt