name: Test Modular Ochestration

on:
  - push

env:
  PYTHON_VERSION: 3.11.4
jobs:
  test:
    runs-on: windows-2022
    name: test goooo
    permissions:
      contents: write # for creating a release
    steps:
      - uses: actions/checkout@v4
      - uses: DoubtfulJerboa/jsaction/actions/python-embed-setup@v12
        with:
          PYTHON_VERSION: 3.12.4
          REQUIREMENTS_PATH: ./requirements.txt
      - uses: DoubtfulJerboa/jsaction/actions/fetch-nssm@v12
      - run: ls

      - uses: DoubtfulJerboa/jsaction/actions/compile-inno-setup@v13
        with:
          ISS_PATH: ./setup.iss
        env:
          GITHUB_TOKEN: ${{ github.token }}